### ISSUE TITLE
If the protocol web:mastodon is not configured previously on Firefox, gives an error

### ISSUE THREAD

**Issue by urtzai** [Aly-ve/Mastodon-share-button#5] opened 2018-11-13 08:39 UTC
If the protocol web:mastodon is not configured previously on Firefox, gives an error when opening the new window. It should ask in all browsers what instance you what to Toot

**Comment by Aly-ve** [comment] 2018-11-18 11:14
Hello !
Thanks for your report. I'll check it soon as possible. :)

**Comment by wiktor-k** [comment] 2019-03-29 14:51
Yep, I'm seeing that too. Too bad that I don't remember Mastodon asking me to register the protocol handler in the first place (both in Firefox or in Chrome). On Firefox I just see `web+mastodon://` address being visited that triggers a "bad page".

Too bad that there is no clean solution to follow/share scenarios in the Fediverse, one would think it's a basic use-case... :cry:

**Comment by Aly-ve** [comment] 2019-03-29 14:57
Hello,
The problem is just solved right now. I'm sorry, I've completely forgotten the pull request.
It'll ask you your current instance. :)

**Comment by wiktor-k** [comment] 2019-03-29 14:59
Thanks! :+1: :clap:

**Comment by rugk** [comment] 2019-12-31 19:23
So a PR has been merged, is this fixed?

However, does this project still use/support the `web+mastodon://` protocol handler?
Because in my case, I just saw the popup without any original usage of `web+mastodon://`, although _I think_ (IIRC) it is registered in my browser.

**Comment by rugk** [comment] 2020-01-03 12:16
BTW web+mastodon support has been removed, unfortunately… :thinking: 

See
https://github.com/tootsuite/mastodon/pull/8127

**Comment by Aly-ve** [comment] 2020-01-04 20:41
Hello,

Yes it's working fine. Thanks to @aldatsa and their PR.

**Closed as completed by Aly-ve** 2020-01-04 20:41 UTC
